### ISSUE TITLE
Toast fails to show error message when attempting API calls to the server during network disconnection

### ISSUE THREAD

**Issue by weihanwang** [yuanjian-org/app#92] opened 2023-07-15 00:58 UTC
Browser console shows the following:

<img width="611" alt="image" src="https://github.com/yuanjian-org/app/assets/9847625/bc722549-e8fc-43ff-a846-af1ca94f7ccd">

**Comment by Adagggggg** [comment] 2024-05-15 02:55
The previously reported issue with the toast error message during network disconnections has been resolved already.

Currently, when the network disconnects, if we attempt to update a user, the appropriate error message is displayed as intended:
<img width="1468" alt="disconnect-error" src="https://github.com/yuanjian-org/app/assets/122472773/bcdaefc8-8568-4d82-ad7c-ffd19192cf7d">

Additionally, the spinner error has also already been fixed. The error related to `Cannot read properties of undefined` in the issue screenshot might be caused by [line 32 in trpc.ts](https://github.com/yuanjian-org/app/blob/main/src/trpc.ts#L32). If we remove the question mark of current code `err.data?.code`, a spinner will show up when updating the user during network disconnection:
<img width="1466" alt="code" src="https://github.com/yuanjian-org/app/assets/122472773/f7068dba-fe0f-43f4-bd28-d40c26eea177">

I suggest this issue can be closed. @weihanwang

**Comment by weihanwang** [comment] 2024-05-15 04:09
@Adagggggg 这个bug只有在登录界面上才会复现。

可以这样复现：

1. 在本地退出登录，回到 http://localhost:3000/auth/login 这一页。

2. 然后停掉后台的 postgres db。比如，如果你用的是 mac 和 homebrew，在terminal运行这个命令：$ brew services stop postgresql

3. 在登录界面输入email以后点击“登录 / 注册”

**Comment by Adagggggg** [comment] 2024-05-16 19:52
Fixed in [pr#279 ](https://github.com/yuanjian-org/app/pull/279)

**Closed by Adagggggg** 2024-05-16 19:52 UTC
Labels: bug, starter
